### ISSUE TITLE
hw: build errors with -std=gnu++20

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode-riscv#4]

**Comment by ssumpf** [comment]
0549767 depends on https://github.com/genodelabs/genode/issues/4894

**Comment by skalk** [comment]
@ssumpf should already be fixed by commit 351f66c32847a360982a5dab03f4566ac16a0024

**Comment by ssumpf** [comment]
> @ssumpf should already be fixed by commit [351f66c](https://github.com/genodelabs/genode-riscv/commit/351f66c32847a360982a5dab03f4566ac16a0024)

Ok, thanks.

**Comment by skalk** [comment]
@ssumpf sorry for the double-work, I had prepared commits for all hw-related external repositories already
